### ISSUE TITLE
torch.fft() related functions are outdated in utils_sisr.py

### ISSUE THREAD

**Issue by HolyWu** [cszn/DPIR#11]
`torch.fft()` related functions were removed since [v1.8.0](https://github.com/pytorch/pytorch/releases/tag/v1.8.0). Instead a [torch.fft](https://pytorch.org/docs/stable/fft.html) module was introduced. Please consider updating the codes in [utils_sisr.py](https://github.com/cszn/DPIR/blob/master/utils/utils_sisr.py) to adapt to the changes. Thank you very much for your hard effort.

**Comment by wbhef** [comment]
May I ask how you solved this problem? Thank you!

**Comment by HolyWu** [comment]
Didn't the author already update it in commit https://github.com/cszn/DPIR/commit/e74732d2f0605503937ce3b55ccefb30b42913ce?
